
# Configure 'Deployment' of mysql server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: database_insta
    tier: database
spec:
  selector: # mysql Pod Should contain same labels
    matchLabels:
      app: database_insta
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: database_insta
        tier: database
  
      containers:
        - env:
            - name: MYSQL_HOST
              value: localhost
            - name: MYSQL_PASS
              value: mypassword
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_USER
              value: user
          image: mysql:8.0.33
          name: database-insta
               
                   
          ports:
            - containerPort: 3306
            
              
---
# Define a 'Service' To Expose mysql to Other Services
apiVersion: v1
kind: Service
metadata:
  name: database_insta
  labels:
    app: database_insta
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:       # mysql Pod Should contain same labels
    app: database_insta
    tier: database
  clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant