version: "3.8"
services:

  db:
    image: 'mysql:8.0.33'
    container_name: 'database_insta'
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: user
      MYSQL_PASS: mypassword
      MYSQL_ROOT_PASSWORD : rootpassword
      MYSQL_PORT: 3306
    
    ports:
      - '3306:3306'
   
      

  go:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: go
    ports: 
      - "9090:8080"
    depends_on: 
    
      - "db"
    
      