apiVersion: apps/v1
kind: Deployment
metadata:
  name: insta-app
spec:
  selector:
    matchLabels:
      app: insta-app
  replicas: 2
  template:
    metadata:
      labels:
        app: insta-app
  
      containers:
        - name: insta-app
          image: algn48/go-insta2
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST  
            - name:  MYSQL_ROOT_PASSWORD  
            - name: DB_USERNAME  
              value: user
            - name: DB_PASSWORD 
              value : mypassword
                 

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: insta-app-svc
  spec:
    selector:
      app: insta-app
    ports:
      - protocol: "TCP"
        port: 8080 # The port that the service is running on in the cluster
        targetPort: 9090 # The port exposed by the service
    type: NodePort # type of the service.